### PR TITLE
[Improvements] embed commit hash into production version of assembly

### PR DESCRIPTION
**Pull request by chucklu**
implemented https://github.com/kerryjiang/SuperSocket/issues/313

### CODE REVIEW

**Comment by chucklu** [comment]
@kerryjiang  I make it.

**Comment by kerryjiang** [comment]
@chucklu the packing step is broken:
https://github.com/kerryjiang/SuperSocket/runs/669537495?check_suite_focus=true

**Comment by chucklu** [comment]
> /usr/share/dotnet/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(77,5): error MSB4018: The "GetPackOutputItemsTask" task failed unexpectedly. [/home/runner/work/SuperSocket/SuperSocket/src/SuperSocket.Channel/SuperSocket.Channel.csproj]
> /usr/share/dotnet/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(77,5): error MSB4018: System.ArgumentException: PackageVersion string specified '2.0.0-preview3(a0348157292533798b77690ab683d2e06f7fa1b2)' is invalid. [/home/runner/work/SuperSocket/SuperSocket/src/SuperSocket.Channel/SuperSocket.Channel.csproj]
> 

PackageVersion string should be file version instead of production version, how did you configure the version check logic?

**Comment by kerryjiang** [comment]
I did nothing. The build script just run nuget pack.

https://github.com/kerryjiang/SuperSocket/blob/master/.github/workflows/myget.yml

**Comment by chucklu** [comment]
I will try to  figure out this 
https://github.com/dotnet/sdk/issues/6572
https://andrewlock.net/version-vs-versionsuffix-vs-packageversion-what-do-they-all-mean/

**Comment by chucklu** [comment]
@kerryjiang  Maybe we can try to remove remove --version-suffix for `dotnet pack` according https://github.com/dotnet/sdk/issues/6572#issuecomment-280820667

**Comment by chucklu** [comment]
remove --verison-suffix did not work.
I guess the problem is caused by the version format.

> VersionSuffix
> 
>     Format: Alphanumberic (+ hyphen) string: [0-9A-Za-z-]*
>     Examples: alpha, beta, rc-preview-2-final
>     Default: (blank)
>     Sets the pre-release label of the version number
> 
> VersionSuffix is used to set the pre-release label of the version number, if there is one, such as alpha or beta. If you don't set VersionSuffix, then you won't have any pre-release labels. VersionSuffix is used to control the Version property, and will **appear in PackageVersion and InformationalVersion**.

I will try to remove '(' and ')' from production.

**Comment by chucklu** [comment]
Fixed the dotnet pack failed through https://github.com/kerryjiang/SuperSocket/pull/346

**Pull request merged**
