### PR TITLE
Add PackageHandlingContextAccessor like HttpContextAccessor

### PR DESCRIPTION
**Pull request by EzrealJ**
Add PackageHandlingContextAccessor to provide the ability to access Session and current package at any location in the HandlePackage process

### CODE REVIEW

**Review by kerryjiang — APPROVED** [review]
Looks nice, thank you!

**Comment by kerryjiang** [comment]
@EzrealJ 
Hello, the test case you added failed:
https://github.com/kerryjiang/SuperSocket/runs/1152983508?check_suite_focus=true#step:6:3502

**Comment by EzrealJ** [comment]
Bad news。
I retried this test in Visual Studio;The test passed
Maybe it’s because I want to pass ITestOutputHelper

**Comment by EzrealJ** [comment]
Do I need to resubmit it?

**Pull request merged**
