### PR TITLE
[Fixing] avoid dotnet pack failed

### PR DESCRIPTION
**Pull request by chucklu**
make the product version matches Format: Alphanumberic (+ hyphen) string: [0-9A-Za-z-]* to avoid dotnet pack failed error

### CODE REVIEW

**Comment by chucklu** [comment]
It will not failed when run dotnet pack command https://github.com/ChuckFork/SuperSocket/runs/670291411?check_suite_focus=true

**Comment by chucklu** [comment]
By the way the previous production should be correct, I believe it's the problem of NuGet.Build.Tasks.Pack

> NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(77,5): error MSB4018: System.ArgumentException: PackageVersion string specified '2.0.0-preview3(a034815)' is invalid.

The previous version format followed https://www.nuget.org/packages/Microsoft.AspNet.Mvc/
image

**Comment by chucklu** [comment]
I filed a new issue here https://github.com/NuGet/Home/issues/9560 for NuGet pack.

**Comment by kerryjiang** [comment]
Can we still keep nuget package's version short and let the assembly's version in this format?

**Comment by chucklu** [comment]
Waiting for https://github.com/ygoe/NetRevisionTask/issues/5, this library set the package version with the value of informational version.

**Comment by kerryjiang** [comment]
Does it mean we can fix it by adding the packageVersion node?

**Comment by chucklu** [comment]
Another approach is https://andrewlock.net/version-vs-versionsuffix-vs-packageversion-what-do-they-all-mean/

> if you're creating a NuGet package with dotnet pack, and you want to override the PackageVersion, you'll need to use MSBuild property overrides
> 
> dotnet pack --no-build /p:PackageVersion=9.9.9-beta

We can override the package version when we run the `dotnet pack` command
https://github.com/kerryjiang/SuperSocket/blob/master/.github/workflows/myget.yml#L32

**Comment by kerryjiang** [comment]
@chucklu Nerdbank.GitVersioning looks better than NetRevisionTask. I have started using it.

**Comment by chucklu** [comment]
@kerryjiang  Thanks for your message, how do you find this new library? I will try to use it later.

**Comment by kerryjiang** [comment]
@chucklu Somebody twittered it and it is a .NET Foundation found project.

**Pull request merged**
