### PR TITLE
V1.6

### PR DESCRIPTION
**Pull request by benjolsen**
I put a try block around the Session creation so that if the new socket connection goes away before it is fully initialized, it won't crash the whole server because of an unhandled exception.

### CODE REVIEW

**Comment by kerryjiang** [comment]
The exception still will be thrown?

**Comment by chucklu** [comment]
@kerryjiang  There is no catch block, so the exception will  be thrown.
@benjolsen  Do you know the exception will be thrown, when you only use try{} finally{}

**Comment by kerryjiang** [comment]
Yes, I have the same question.

**Comment by benjolsen** [comment]
Yes, you are correct.  I will change to an empty catch block

**Comment by benjolsen** [comment]
Closing this pull request since I sent an unwanted change to the project file and I can't figure out how to undo it.

**Pull request closed without merging**
