### PR TITLE
Upgraded core5.0

### PR DESCRIPTION
**Pull request by renjthmails**
Upgraded with .NET5.0 (Core)

### CODE REVIEW

**Comment by renjthmails** [comment]
Hi Kerry,
TestMutlipleServerHost seems to be failing.
Others test cases are working fine

image

**Comment by kerryjiang** [comment]
Hello renjthmails, Netstandard2.1 should be compatible with Net5.0.
We don't need upgrade all the libraries' target to net5.0, correct?

**Comment by kerryjiang** [comment]
And if we upgrade to net5.0 directly, it will break all the netcore3.1 applications.

**Comment by renjthmails** [comment]
Yes, you are right. But we don't have dependency on Netstandard specific libraries. The same dlls are part of the core framework as well and it is backward compatible too. There were some gaps (refs to standard libraries) with the sample projects, which are resolved and pushed now. 

I could able to run all the sample apps except the Livechat one. It is having a dependency on the Angular clientapp and I dont have a background of Angular to fix that. Just removing the dependency on standard libraries will do the magic. 

I could have given a try if it were Knockout or React.

**Comment by kerryjiang** [comment]
@renjthmails I think finally the dependences should be the actual platform's assemblies, netstandard is just an abstraction.

I just did a fix for the LiveChat sample, it should be able to run on net5 directly without problem.
Let me know if you still meet any problem with this sample.
https://github.com/kerryjiang/SuperSocket/commit/7ef1483de7c500aad72ee04be5991cf301e60f8c

**Comment by renjthmails** [comment]
That s Great!!! Sure, I ll check and confirm back.
Thank you for your swift response and action.

**Comment by renjthmails** [comment]
@kerryjiang As per my analysis, currently the gap is w.r.t the particular testcase : TestMultipleServerHost only. Not sure whether it has got introduced as part of the up-gradation. If it is not a major concern can we get it merged to the master ?

**Comment by kerryjiang** [comment]
@renjthmails Hello, I meant we don't need upgrade the target. net5 application can reference netstandard library without issue just like what LiveChat sample does. Your PR seems not necessary, because it will break the compatibility for the NetCoreApp3.1.  What's the problem you met when you use SuperSocket in a net5 application?

**Comment by kerryjiang** [comment]
@renjthmails I think SuperSocket 2.0 totally works with dotnet5.

**Comment by renjthmails** [comment]
Fine Kerry. By seeing many requests for .NET 5.0 i have given it a shot. By
seeing the references on .NET Framework dlls people may be reluctant to use
that.
Even I also had a similar thought initially.

**Comment by kerryjiang** [comment]
Ok, probably I will provide binaries on net5 in the nuget packages at the same time.

**Comment by renjthmails** [comment]
Ya, that s good.

**Comment by kerryjiang** [comment]
The packages of 2.0.0-beta.10 include the net5 compatible assemblies.

**Pull request closed without merging**
