### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by chucklu**
fix typo reported by Resahrper

### CODE REVIEW

**Comment by chucklu** [comment]
By the way, Resharper also reported Configurate and Handshaked, they might be Configure and Handshook. However, I am not pretty sure about them.

**Comment by kerryjiang** [comment]
Thank you!

**Comment by kerryjiang** [comment]
I will check Configurate and Handshaked.

**Comment by chucklu** [comment]
Hi @kerryjiang ,
     I suggest to use a better branch merge policy next time. It's called as [Semi-linear merge](https://devblogs.microsoft.com/devops/pull-requests-with-rebase/#semi-linear-merge).
    _Some people think of this as the best of both worlds: individual commits are retained, so that you can see how the work evolved, but instead of just being rebased, a “merge bubble” is shown so that you can immediately see the work in each individual pull request._

   However github did not support this feature https://github.com/isaacs/github/issues/1143, you might fetch the forked repository to local repository by adding another remote and fetch it.
   Then you can do the Semi-linear merge manually.

**Pull request merged**
